import Combatant from "../models/Combatant.js";
import { DAMAGE_TYPES,getPierceRatio } from "../data/damageTypes.js";
import { analyseAttack } from "../engine/simulator.js";
import { saveState,loadState,clearState,downloadJson } from "../storage/storage.js";

const state={player:new Combatant("Player"),boss:new Combatant("Boss"),activeBossAttack:0,results:[],chart:null};
const el={player:document.querySelector("#playerPanel"),boss:document.querySelector("#bossPanel"),results:document.querySelector("#results"),log:document.querySelector("#combatLog"),chartCanvas:document.querySelector("#damageChart"),fallback:document.querySelector("#chartFallback"),validation:document.querySelector("#validation"),rollCount:document.querySelector("#rollCount"),showLog:document.querySelector("#showLog"),showChart:document.querySelector("#showChart"),calculate:document.querySelector("#calculateBtn"),roll:document.querySelector("#rollBtn"),save:document.querySelector("#savePresetBtn"),load:document.querySelector("#loadPresetBtn"),export:document.querySelector("#exportBtn"),import:document.querySelector("#importInput"),clear:document.querySelector("#clearBtn")};
const n=v=>Math.max(0,Number(v)||0), chance=v=>Math.max(0,Math.min(100,Number(v)||0)), integer=(v,min=1)=>Math.max(min,Math.floor(Number(v)||min)), fmt=v=>Math.round(v).toLocaleString();
function damageOptions(selected){return DAMAGE_TYPES.map(t=>`<option value="${t.name}" ${t.name===selected?"selected":""}>${t.name} (${Math.round(t.pierce*100)}%)</option>`).join("");}
function renderCombatant(container,combatant,isBoss=false){const attack=isBoss?combatant.attacks[state.activeBossAttack]:combatant.attacks[0];container.innerHTML=`<h2>${combatant.name}</h2><div class="section-title">Defender stats</div><div class="form-grid"><label>Health <input data-field="health" type="number" min="0" value="${combatant.health}"></label><label>Armour <input data-field="armour" type="number" min="0" value="${combatant.armour}"></label><label>Block Chance % <input data-field="blockChance" type="number" min="0" max="100" value="${combatant.blockChance}"></label><label>Block Damage <input data-field="blockDamage" type="number" min="0" value="${combatant.blockDamage}"></label></div><div class="section-title">Terrain</div><div class="terrain-row"><label class="check"><input data-terrain="highGround" type="checkbox" ${combatant.terrain.highGround?"checked":""}> High Ground</label><label class="check"><input data-terrain="razorWire" type="checkbox" ${combatant.terrain.razorWire?"checked":""}> Razor Wire</label><label class="check"><input data-terrain="trench" type="checkbox" ${combatant.terrain.trench?"checked":""}> Trench</label></div>${isBoss?renderTabs():""}<div class="section-title">${attack.name}</div>${renderAttack(attack,isBoss)}`;bind(container,combatant,isBoss);}
function bind(container,combatant,isBoss){container.querySelectorAll("[data-field]").forEach(i=>i.addEventListener("input",()=>combatant[i.dataset.field]=i.dataset.field.includes("Chance")?chance(i.value):n(i.value)));container.querySelectorAll("[data-terrain]").forEach(i=>i.addEventListener("change",()=>{const k=i.dataset.terrain;combatant.terrain[k]=i.checked;if(k==="trench"&&i.checked)combatant.terrain.razorWire=false;if(k==="razorWire"&&i.checked)combatant.terrain.trench=false;render();}));if(isBoss)container.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{state.activeBossAttack=Number(b.dataset.index);render();}));const attack=isBoss?combatant.attacks[state.activeBossAttack]:combatant.attacks[0];const enabled=container.querySelector("[data-attack-enabled]");if(enabled)enabled.addEventListener("change",()=>{attack.enabled=enabled.checked;render();});container.querySelectorAll("[data-attack-field]").forEach(i=>{const update=()=>{const k=i.dataset.attackField;if(k==="damageType"){attack.damageType=i.value;attack.pierceRatio=getPierceRatio(i.value);}else if(k==="hits")attack.hits=integer(i.value,1);else if(k.includes("Chance"))attack[k]=chance(i.value);else attack[k]=n(i.value);};i.addEventListener("input",update);i.addEventListener("change",update);});}
function renderTabs(){return `<div class="tabs">${state.boss.attacks.map((a,i)=>`<button class="tab ${i===state.activeBossAttack?"active":""}" data-index="${i}">${a.name}${a.enabled||i===0?"":" · off"}</button>`).join("")}</div>`;}
function renderAttack(a,isBoss){return `<div class="attack-card">${isBoss&&a.name!=="Attack"?`<label class="check"><input data-attack-enabled type="checkbox" ${a.enabled?"checked":""}> Enable ${a.name}</label>`:""}<div class="form-grid"><label>Damage <input data-attack-field="damage" type="number" min="0" value="${a.damage}"></label><label>Hits <input data-attack-field="hits" type="number" min="1" value="${a.hits}"></label><label>Damage Type <select data-attack-field="damageType">${damageOptions(a.damageType)}</select></label><label>Crit Chance % <input data-attack-field="critChance" type="number" min="0" max="100" value="${a.critChance}"></label><label>Crit Damage <input data-attack-field="critDamage" type="number" min="0" value="${a.critDamage}"></label></div></div>`;}
function validate(){const msgs=[];if(state.player.attacks[0].damage<=0)msgs.push("Player attack damage should be greater than 0.");if(state.player.attacks[0].hits<1)msgs.push("Player hits must be at least 1.");state.boss.attacks.filter(a=>a.enabled).forEach(a=>{if(a.damage<=0)msgs.push(`${a.name} damage should be greater than 0.`);if(a.hits<1)msgs.push(`${a.name} hits must be at least 1.`);});el.validation.innerHTML=msgs.length?msgs.map(m=>`<div>${m}</div>`).join(""):`<div class="ok">Ready.</div>`;return !msgs.length;}
function run(){const rolls=Math.min(100,integer(el.rollCount.value,1));el.rollCount.value=rolls;validate();const results=[];results.push({direction:"Player → Boss",...analyseAttack(state.player,state.boss,state.player.attacks[0],"playerToBoss",rolls)});state.boss.attacks.filter(a=>a.enabled).forEach(a=>results.push({direction:"Boss → Player",...analyseAttack(state.boss,state.player,a,"bossToPlayer",rolls)}));state.results=results;renderResults();renderLog();renderChart();}
function renderResults(){if(!state.results.length){el.results.innerHTML=`<p class="hint">Enter stats and press Calculate.</p>`;return;}el.results.innerHTML=state.results.map(r=>`<div class="result-group"><h3>${r.direction}: ${r.name}</h3><div class="results-grid"><div class="metric"><span>Expected</span><strong>${fmt(r.expected)}</strong></div><div class="metric"><span>Minimum</span><strong>${fmt(r.minimum)}</strong></div><div class="metric"><span>Maximum</span><strong>${fmt(r.maximum)}</strong></div><div class="metric"><span>Simulation avg</span><strong>${fmt(r.simulationAverage)}</strong></div><div class="metric"><span>Lowest roll</span><strong>${fmt(r.lowest)}</strong></div><div class="metric"><span>Highest roll</span><strong>${fmt(r.highest)}</strong></div><div class="metric"><span>Crit hits</span><strong>${r.crits}</strong></div><div class="metric"><span>Blocked hits</span><strong>${r.blocks}</strong></div></div></div>`).join("");}
function renderLog(){if(!el.showLog.checked||!state.results.length){el.log.innerHTML=`<p class="hint">Combat log hidden.</p>`;return;}el.log.innerHTML=state.results.map(r=>{const lines=(r.logs[0]??[]).map(h=>`Hit ${h.hit}: roll ${(h.variance*100).toFixed(1)}% | crit ${h.crit?"yes":"no"} | block ${h.block?"yes":"no"} | damage ${fmt(h.damage)}`).join("\n");return `<div class="log-entry">${r.direction}: ${r.name}\n${lines||"No hits."}</div>`;}).join("");}
function buckets(values){const min=Math.min(...values),max=Math.max(...values),count=8,b=Array.from({length:count},()=>0);values.forEach(v=>{const idx=max===min?0:Math.min(count-1,Math.floor(((v-min)/(max-min))*count));b[idx]++;});return b.map((count,i)=>({label:`${fmt(min+((max-min)/8)*i)}–${fmt(min+((max-min)/8)*(i+1))}`,count}));}
function renderChart(){if(!el.showChart.checked||!state.results.length){el.chartCanvas.style.display="none";el.fallback.innerHTML=`<p class="hint">Chart hidden.</p>`;if(state.chart){state.chart.destroy();state.chart=null;}return;}el.chartCanvas.style.display="block";const data=buckets(state.results[0].simulations);el.fallback.innerHTML="";if(window.Chart){if(state.chart)state.chart.destroy();state.chart=new Chart(el.chartCanvas,{type:"bar",data:{labels:data.map(d=>d.label),datasets:[{label:"Rolls",data:data.map(d=>d.count)}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{x:{ticks:{color:"#bbb5a8"}},y:{ticks:{color:"#bbb5a8",precision:0}}}}});}else{const top=Math.max(...data.map(d=>d.count));el.fallback.innerHTML=data.map(d=>`<div class="bar-row"><span>${d.label}</span><div><div class="bar" style="width:${top?d.count/top*100:0}%"></div></div><span>${d.count}</span></div>`).join("");}}
function plain(){return{player:state.player,boss:state.boss};}
function hydrate(data){state.player=Combatant.from(data?.player??{},"Player");state.boss=Combatant.from(data?.boss??{},"Boss");state.activeBossAttack=0;state.results=[];render();}
function render(){renderCombatant(el.player,state.player,false);renderCombatant(el.boss,state.boss,true);renderResults();if(!state.results.length){el.log.innerHTML=`<p class="hint">No combat log yet.</p>`;el.fallback.innerHTML=`<p class="hint">No chart yet.</p>`;}}
el.calculate.addEventListener("click",run);el.roll.addEventListener("click",run);el.showLog.addEventListener("change",renderLog);el.showChart.addEventListener("change",renderChart);el.save.addEventListener("click",()=>{saveState(plain());alert("Preset saved in this browser.");});el.load.addEventListener("click",()=>{const d=loadState();if(!d){alert("No saved preset found.");return;}hydrate(d);});el.clear.addEventListener("click",()=>{clearState();location.reload();});el.export.addEventListener("click",()=>downloadJson("tacticus-damage-calculator-preset.json",plain()));el.import.addEventListener("change",async()=>{const file=el.import.files[0];if(!file)return;try{hydrate(JSON.parse(await file.text()));}catch{alert("Could not import that JSON file.");}el.import.value="";});
render();
