import { DAMAGE_VARIANCE,TERRAIN } from "../config/constants.js";
const clampPct=v=>Math.max(0,Math.min(100,Number(v)||0))/100;
function terrainMultiplier(attackerTerrain,defenderTerrain,mode){let m=0;if(mode==="playerToBoss"){if(attackerTerrain.highGround)m+=TERRAIN.HIGH_GROUND;}else{if(attackerTerrain.highGround)m+=TERRAIN.HIGH_GROUND;if(defenderTerrain.trench)m+=TERRAIN.TRENCH;else if(defenderTerrain.razorWire)m+=TERRAIN.RAZOR_WIRE;}return Math.max(0,1+m);}
function baseHit(attack,variance,armour){const d=attack.damage*variance;return Math.max(d-armour,d*attack.pierceRatio);}
function hitDamage({attack,attacker,defender,variance,crit,block,mode}){const dmg=crit?attack.damage+attack.critDamage:attack.damage;const d=dmg*variance;const after=Math.max(d-defender.armour,d*attack.pierceRatio);const modified=after*terrainMultiplier(attacker.terrain,defender.terrain,mode);return Math.max(0,block?modified-defender.blockDamage:modified);}
export function deterministicAttack(attacker,defender,attack,mode,variance=DAMAGE_VARIANCE.AVG){const cp=clampPct(attack.critChance),bp=clampPct(defender.blockChance);let total=0;for(let h=1;h<=attack.hits;h++){const cProb=Math.pow(cp,h);const bProb=Math.pow(bp,h);const nn=hitDamage({attack,attacker,defender,variance,crit:false,block:false,mode});const nb=hitDamage({attack,attacker,defender,variance,crit:false,block:true,mode});const cn=hitDamage({attack,attacker,defender,variance,crit:true,block:false,mode});const cb=hitDamage({attack,attacker,defender,variance,crit:true,block:true,mode});total+=(1-cProb)*((1-bProb)*nn+bProb*nb)+cProb*((1-bProb)*cn+bProb*cb);}return total;}
export function minAttack(attacker,defender,attack,mode){const block=clampPct(defender.blockChance)>0;let t=0;for(let i=0;i<attack.hits;i++)t+=hitDamage({attack,attacker,defender,variance:DAMAGE_VARIANCE.MIN,crit:false,block,mode});return t;}
export function maxAttack(attacker,defender,attack,mode){const crit=clampPct(attack.critChance)>0;let t=0;for(let i=0;i<attack.hits;i++)t+=hitDamage({attack,attacker,defender,variance:DAMAGE_VARIANCE.MAX,crit,block:false,mode});return t;}
function chainedFlags(chance,hits){const p=clampPct(chance),out=[];let active=true;for(let i=0;i<hits;i++){if(!active||p<=0){out.push(false);continue;}const ok=Math.random()<p;out.push(ok);if(!ok)active=false;}return out;}
export function rollAttack(attacker,defender,attack,mode){const critFlags=chainedFlags(attack.critChance,attack.hits);const blockFlags=chainedFlags(defender.blockChance,attack.hits);let total=0,crits=0,blocks=0;const log=[];for(let i=0;i<attack.hits;i++){const variance=DAMAGE_VARIANCE.MIN+Math.random()*(DAMAGE_VARIANCE.MAX-DAMAGE_VARIANCE.MIN);const crit=critFlags[i],block=blockFlags[i];if(crit)crits++;if(block)blocks++;const damage=hitDamage({attack,attacker,defender,variance,crit,block,mode});total+=damage;log.push({hit:i+1,variance,crit,block,damage});}return{total,crits,blocks,log};}
